version: '3.8'

services:
  website:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next 